### ISSUE TITLE
Does not work as a CommonJS Module

### ISSUE THREAD

**Issue by evanshortiss** [feedhenry/fh-sync-js#40]
When using this in a project with browserify or similar tools it fails to work. It gives this error in my Ionic 2 + Angular 4 project - `ERROR Error: Uncaught (in promise): TypeError: Lawnchair is not a function`

I haven't looked into the exact differences, but it appears that in `sync-client.js` we load `var Lawnchair = require('../libs/lawnchair/lawnchair');` but this does not have `module.exports`. When I added this it then gives the error `Error: Uncaught (in promise): Error: No valid adapter.`

I will look to make a PR.

**Comment by wtrocki** [comment]
Really important issue that was already mentioned many times. 
This is happening due to browserify-shim module missing in the top level project.

For now we have workaround to include it in client projects.
Example: 
https://github.com/feedhenry-raincatcher/raincatcher-core/pull/199

**Comment by evanshortiss** [comment]
@wtrocki I recall making that fix in the [JS SDK](https://github.com/feedhenry/fh-js-sdk/pull/211), but I don't think it will work here since the issue is at a source level. Will look into it though, thanks for the feedback!

**Comment by camilamacedo86** [comment]
Hi @evanshortiss,

Are you sing as follows and facing issues? I don't think you are calling it properly since the suit test has been working on perfectly with the latest versions of FHC. Could you please check how are you doing it and if it is in the way described in the README of the project?

```
 fhc.env.list({app:'hgxe4z5j2b6owln5vw6qvx5i', env:'dev', json : true }, function (err,res) {
      return cb( res);
    });
```
For further information check the README [here](https://github.com/feedhenry/fh-fhc#as-a-nodejs-module).

Cheers, 
Camila Macedo
